config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope "/admin" do
    resources :users do
      get 'count_unread_messages', on: :member
      get 'unread_messages', on: :member
      resources :messages
    end
  end

  root 'users#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :author, class_name: "User"
  validates :title, presence: true
  scope :between, -> (author_id, recipient_id) do
    includes(:author).where("(author_id = ? AND recipient_id = ?) or (author_id = ? AND recipient_id = ?)", author_id, recipient_id, recipient_id, author_id)
  end

  def recipient
    User.find(recipient_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :rememberable, :validatable
  has_many :messages, foreign_key: "author_id"

  def collect_unread
    Message.where("read = ? and recipient_id = ?", false, self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_out_path_for(user)
    user_session_path
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: :show

  def show
    @user = User.find(params[:user_id])
    @message.update(read: true)
  end

  # POST /messages
  def create
    @user = User.find(params[:user_id])
    @message = current_user.messages.new(message_params)
    @messages = Message.between(current_user.id, @user.id)

    if @message.save
      redirect_to user_path(@user), notice: 'Message was sent to this user.'
    else
      render template: '/users/show'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def message_params
      params.require(:message).permit(:title, :body, :author_id, :recipient_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :deny_access, only: [:new, :create, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @message = Message.new
    @messages = Message.between(current_user.id, @user.id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if user_params[:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if user_params[:admin].present? && !current_user.admin?
      params[:user].delete(:admin)
    end

    successfully_updated = if needs_password?(@user, user_params)
                             @user.update(user_params)
                           else
                             @user.update_without_password(user_params)
                           end

    if successfully_updated
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  def count_unread_messages
  end

  def unread_messages
    @messages = current_user.collect_unread
  end

  protected

    def needs_password?(user, params)
      params[:password].present?
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
    end

    def deny_access
      unless current_user.admin? || current_user == @user
        flash[:alert] = 'You are not allowed to perform this action'
        redirect_to '/admin/users'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TicketsUa" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <a class="navbar-brand" href="#">TicketsUa</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <%= render 'menu/menu_items' %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/menu/_menu_items.html.erb
<% if user_signed_in? %>
  <li>  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %> </li>
<% else %>
  <li><%= link_to('Login', new_user_session_path) %></li>
<% end %>
<li class="user-name">User:
<% if current_user %>
  <%= current_user.email %>,
    your ID: <span class="user-id"> <%= current_user.id %> </span></li>
<% else %>
  (not logged in)</li>
<% end %>
<%= render "menu/new_messages_information" %>
<li class="renew-link"><%= button_to "Count new messages", count_unread_messages_user_path(current_user), method: :get, remote: true if current_user%></li>

app/views/menu/_new_messages_information.html.erb
<% if current_user && current_user.collect_unread.any? %>
  <li class="unread-messages">
    <%= link_to(unread_messages_user_path(current_user)) do %>
      <strong>You have <%= current_user.collect_unread.count %> new messages</strong>
    <% end %>
  </li>
<% else %>
  <li class="old-messages">
    <strong>You don't have new messages</strong>
  </li>
<% end %>

app/views/messages/show.html.erb
<p>
  <strong>Author:</strong>
  <%= @message.author.name %>
</p>
<p>
  <strong>Receiver:</strong>
  <%= @message.recipient.name %>
</p>
<p>
  <strong>Date:</strong>
  <%= @message.created_at %>
</p>
<p>
  <strong>Title:</strong>
  <%= @message.title %>
</p>
<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>
  <strong>Reply to this message</strong>

  <%= form_for [@user, current_user.messages.new] do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.text_field :title, placeholder: :title %> </br>
  </p>
  <p>
    <%= f.text_area :body, cols: 70, placeholder: :body_of_message %></br>
  </p>
    <%= f.hidden_field :recipient_id, value: @user.id %></br>

    <%= f.submit 'Send message' %>
  <% end %>

<%= link_to(user_path(@user)) do %>
  <span>Back to conversation with <%= @user.name %></span>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/count_unread_messages.js.erb
$('.unread-messages, .old-messages').replaceWith("<%= escape_javascript(render 'menu/new_messages_information') %>");

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New User', new_user_path if current_user.admin? %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Admin:</strong>
  <% if @user.admin? %>
    Yes
  <% else %>
    No
  <% end %>
</p>
<p>
<div class= <%= @user == current_user ? "hidden" : "conversation" %> >
<strong>Your conversation with <%= @user.name %></strong>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Date</th>
      <th>Body</th>
    </tr>
  </thead>
  <tbody>
  <% @messages.each do |message| %>
  <tr>
    <td>
      <%= link_to message.title, user_message_path(@user, message) %>
    </td>
    <td>
      <%= message.author.name %>
    </td>
    <td>
      <%= message.created_at %>
    </td>
    <td>
      <%= truncate(message.body, length: 60) %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>
  <strong>Send a message</strong>

  <%= form_for [@user, @message] do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.text_field :title, placeholder: :title %> </br>
  </p>
  <p>
    <%= f.text_area :body, cols: 70, placeholder: :body_of_message %></br>
  </p>
    <%= f.hidden_field :recipient_id, value: @user.id %></br>

    <%= f.submit 'Send message' %>
  <% end %>
</p>
</div>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/unread_messages.html.erb
<h2>Here is your new messages</h2>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Date</th>
      <th>Body</th>
    </tr>
  </thead>
  <tbody>
  <% @messages.each do |message| %>
  <tr>
    <td>
      <%= link_to message.title, user_message_path(message.author, message) %>
    </td>
    <td>
      <%= message.author.name %>
    </td>
    <td>
      <%= message.created_at %>
    </td>
    <td>
      <%= truncate(message.body, length: 60) %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'To the list of users', users_path %>